cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

handler500 = 'shop.views.handler500'

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webpush/', include('webpush.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'orders'

urlpatterns = [
    path('admin/', views.order_list, name='order_list'),
    path('create/', views.create_order, name='create_order'),
    path('process/<int:order_id>', views.process_order, name='process_order'),
    path('process/table/<int:table_number>', views.process_table, name='process_table'),
    path('takeout/process', views.create_order_admin, name='create_order_admin'),
]

orders/models.py
from django.db import models
from shop.models import Item
from django.db.models import signals
from django.dispatch import receiver
from webpush import send_user_notification 
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

class Table(models.Model):
    number = models.IntegerField()

    class Meta: 
        ordering = ('-number',)

    def __str__(self):
        return str(self.number)


class Order(models.Model):
    table = models.IntegerField()
    total = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)
    processed = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)


    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

@receiver(signals.post_save, sender=Order)
def create_order(sender, instance, created, **kwargs):
    print("order created")
    user = get_object_or_404(User, pk=1)
    print(user)
    payload = {"head": "Welcome!", "body": "Hello World"}
    send_user_notification(user=user, payload=payload, ttl=1000)


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                    related_name='items',
                    on_delete=models.CASCADE)
    item = models.ForeignKey(Item,
                    related_name='order_items',
                    on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Cart
from .models import OrderItem, Order, Table

def order_list(request):
    if request.user.is_superuser:
        orders = Order.objects.filter(processed=False)
        order_items = OrderItem.objects.all()
        tables = Table.objects.all()
        processed_orders = Order.objects.filter(processed=True, paid=False)
        active_tables = []
        for order in processed_orders:
            if order.table not in active_tables:
                active_tables.append(order.table)
        return render(request, 'orders_list.html', {'orders': orders, 'order_items': order_items, 'tables': active_tables, 'proc_orders': processed_orders })


def create_order(request):
    cart = Cart(request)
    if (request.user_agent.is_mobile or request.user_agent.is_tablet) and cart.__len__() > 0:
        if request.method == 'POST':
            if 'table_id' in request.session:
                table_id = request.session['table_id']
            else:
                return render(request, 'please.html')
            order = Order.objects.create(table=table_id, total=cart.get_total_price(), paid=False)
            for item in cart:
                OrderItem.objects.create(order=order,
                                item=item['item'],
                                price=item['price'],
                                quantity=item['quantity'])
            del request.session['table_id']
            request.session.modified = True                    
            cart.clear()
            return render(request,
                        'created.html',
                        {'order': order})
        else:
            return render(request,
                    'create.html',
                    {'cart': cart})
    else:
        return render(request, 
                    'please.html')
            
def process_order(request, order_id):
    if request.user.is_superuser:
        order = get_object_or_404(Order, id=order_id)
        print(order)
        order_items = OrderItem.objects.filter(order=order)
        for item in order_items: 
            print(item.item)
        Order.objects.filter(id=order_id).update(processed=True)
        return redirect(request.META['HTTP_REFERER'])


def process_table(request, table_number):
    if request.user.is_superuser:
        table = get_object_or_404(Table, number=table_number)
        orders = Order.objects.filter(table=table.number, processed=True, paid=False)
        order_items = OrderItem.objects.all()
        total = 0
        for order in orders: 
            for item in order_items:
                if item.order == order:
                    print(str(item.item)+' '+ str(item.quantity)+ ' ' + str(item.quantity*item.price))
                    total = total + (item.price*item.quantity)
        print("Total: " + str(total) + "SDG")
        #Order.objects.filter(table=table.number, processed=True).update(paid=True)

        return redirect(request.META['HTTP_REFERER'])


def create_order_admin(request):
    if request.user.is_superuser:
        cart = Cart(request)
        for item in cart:
            print(str(item['item']) + ' ' + str(item['quantity']) + ' ' + str(item['price']))
        print(cart.get_total_price())
        cart.clear()
        return redirect('shop:take_out')

orders/templates/create.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
Checkout
{% endblock %}
{% block content %}
<h4 style="text-decoration: underline; text-align: center; font-family: 'Cairo', sans-serif;">{% trans 'Your Order' %}</h4>

<div class="card" style="float: center;">
  <div class="card-body" style="float: center;">
    <p class="card-text">
        {% for item in cart %}
            <div class="row">
            <div class="col col-md-6 col-sm-4">
            <p style="overflow-wrap: break-word;">{{ item.quantity }} {{ item.item.name }}</p>
            </div>
            <div class="col col-md-6 col-sm-8">
            <span style="float: right;">{{ item.total_price }}</span>
            </div>
            <br>
            </div>
        {% endfor %}
    <hr>
    <p><b>Total: <span style="float: right;">{{ cart.get_total_price }} SDG</span></b></p>
    </p>
    
  </div>
</div> <br>
<form action="." method="post" class="order-form"  style="float: center; text-align: center;">
    <button type="submit" class="btn" style="color: white; background-color: #eb842d;">{% trans 'Place Order' %}</button>
    {% csrf_token %}
</form>
{% endblock %}

orders/templates/created.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
Thank you
{% endblock %}
{% block content %}
<br>
<div class="card" style="float: center;">
  <div class="card-body" style="float: center;">
    <p class="card-text">
        <h1 class="sus" style="color: #eb842d;">{% trans 'Thank you' %}</h1>
        <p class="sus">{% trans 'Your order has been successfully completed. Your order number is' %}
    <strong>{{ order.id }}</strong>.</p>
    </p>
    
  </div>
</div> <br>
<hr>
    <h4 style="text-decoration: underline; text-align: center;" class="sus"> {% trans 'Scan QR Code if you want to make another order' %} </h4>
    <img src="{% static 'img/qr.jpg' %}" height="300" width="380"/>


{% endblock %}

orders/templates/orders_list.html
{% extends "base.html" %}
{% block title %}
Orders Management
{% endblock %}
{% block content %}
<br>
<div class="row" style="float: center;">
  <div class="col col-lg-3"></div>
  <div class="col col-lg-5" id="notifylist">
  <br>
  </div>
</div>
<div class="row">
  <div class="col col-md-5">
    <h2 style="text-decoration: underline; text-align: center;"><span class="badge badge-warning">Orders</span></h2>
    <div id="accordion">
      {% for order in orders %}
      <div class="card">
        <div class="card-header" id="heading{{ order }}">
          <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ order }}" aria-expanded="true"
              aria-controls="collapse{{ order }}">
              <b>Order No. {{ order.id }} at Table {{order.table}}</b>
            </button>
            <a href="{% url 'orders:process_order' order_id=order.id %}"><i class="fas fa-print"
                style="float: right; text-align: right; font-size: 27px;"></i></a>
          </h5>
        </div>

        <div id="collapse{{ order }}" class="collapse hide" aria-labelledby="heading{{ order }}"
          data-parent="#accordion">
          <div class="card-body">
            {% for item in order_items %}
            {% if item.order == order %}


            {{ item.quantity }} {{ item.item }}<br>

            {% endif %}
            {% endfor %}
            <hr> <b>Total</b> <b style="float:right;">{{ order.total }}</b>
          </div>
        </div>
      </div>
      <br>
      {% endfor %}
    </div>
  </div>
  <div class="col col-md-2">
  </div>
  <div class="col col-md-5">
    <h2 style="text-decoration: underline; float: center; text-align: center;"><span
        class="badge badge-warning">Tables</span></h2>
        {% for table in tables %}
    <div id="accordion">
      
      <div class="card">
        <div class="card-header" id="{{ table }}">
          <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ table }}" aria-expanded="true"
              aria-controls="{{ table }}">
              <i class="fas fa-circle" style="color: green; font-size: 13px;"></i> <b>TABLE {{ table }}</b>
            </button>
            <a href="{% url 'orders:process_table' table_number=table %}"><i class="fas fa-clipboard-check"
                style="float: right; text-align: right; font-size: 27px;"></i></a>
          </h5>
        </div>

        <div id="collapse{{ table }}" class="collapse hide" aria-labelledby="{{ table }}" data-parent="#accordion">
          <div class="card-body">
            {% for order in proc_orders %}
            {% if order.table == table %}
            <b style="font-size: 25px;"><span class="badge badge-pill badge-warning">{{ order }}</span> </b> <br>
            {% for i in order_items %}
            {% if i.order == order %}
            {{ i.quantity }} {{ i.item }}<br>
            {% endif %}
            {% endfor %}
            <hr> <b>Total</b> <b style="float:right;">{{ order.total }} SDG</b> <br><br>
            {% endif %}

            {% endfor %}
          </div>
        </div>
      </div>
    </div> <br>
    {% endfor %}
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const webSocketBridge = new channels.WebSocketBridge();
    const nl = document.querySelector("#notifylist");

    webSocketBridge.connect('/notifications/');
    webSocketBridge.listen(function (action, stream) {
      console.log("RESPONSE:", action);
      if (action.event == "New Order") {
        console.log("success");
        var el = document.createElement("div");
        el.innerHTML = `<div class="alert alert-warning" role="alert" style="text-align: center;">
                          <h4><i class="far fa-bell"></i> <a href="/orders/admin"> You have a new order at table ${action.table} </a><h4>
                          </div>`;
        /*el.innerHTML = `<div class="alert alert-warning" role="alert" style="text-align: center;">
                        <h4><i class="far fa-bell"></i> You have a new order at ${action.table}<h4>
                        </div>`*/
        nl.appendChild(el);
      }
    })
    document.ws = webSocketBridge; /* for debugging */
  })
</script>
{% endblock %}

orders/templates/please.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
Please Scan QR Code 
{% endblock %}
{% block content %}
<br><br>
<h4 class="sus" style="text-decoration: underline; text-align: center;"> {% trans 'Please Scan QR Code!' %} </h4>
<br>
<img src="{% static 'img/qr.jpg' %}" height="300" width="380"/>
{% endblock %}