cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

handler500 = 'shop.views.handler500'

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webpush/', include('webpush.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('<int:table_id>', views.item_list, name='item_list_by_table'),
    path('<slug:category_slug>/', views.item_list,
    name='item_list_by_category'),
    path('takeout', views.take_out, name='take_out'),
    path('takeout/<slug:category_slug>/', views.take_out, name='take_out_by_category'),

]

shop/models.py
from django.db import models
from .slug import unique_slugify
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def save(self, **kwargs):
        slug = '%s' % (self.name)
        unique_slugify(self, slug)
        super(Category, self).save()

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:item_list_by_category',
        args=[self.slug])


class Item(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    ingredients = models.TextField(max_length=400)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='items/',
                            blank=True)
    available = models.BooleanField(default=True)

    class Meta: 
        ordering = ('name',)
        verbose_name = 'item'
        verbose_name_plural = 'items'

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, render_to_response
from .models import Item, Category
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddItemForm
from cart.cart import Cart
from django.core.paginator import Paginator
import json
from django.template import RequestContext

def handler500(request):
    data = {}
    return render(request, '505.html', data)


def item_list(request, table_id=None, category_slug=None):
    cart = Cart(request)
    category = None
    if table_id != None:
        if 'table_id' not in request.session:
            request.session['table_id'] = str(table_id)
    #print(request.session['table_id'])
    categories = Category.objects.all()
    items = Item.objects.filter(available=True)
    paginator = Paginator(items, 6) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = items.filter(category=category)
        paginator = Paginator(items, 6) 
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

    cart_items = []
    for i in cart:
        cart_items.append(i["item"].name)

    print(cart_items)
    cart_product_form = CartAddItemForm()
    return render(request,
                'list.html',
                {'category': category,
                'categories': categories,
                'items': items,
                'cart': cart,
                'cart_items': cart_items,
                'cart_product_form': cart_product_form,
                'page_obj': page_obj,
                'paginator': paginator
                })


def take_out(request, category_slug=None):
    cart = Cart(request)
    category = None
    categories = Category.objects.all()
    items = Item.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = items.filter(category=category)
    
    cart_items = []
    for i in cart:
        cart_items.append(i["item"].name)
    cart_product_form = CartAddItemForm()
    return render(request, 'takeout.html', {'category': category,
                                             'items': items,
                                             'cart_items': cart_items, 
                                             'cart': cart,
                                             'categories': categories,
                                             'cart_product_form': cart_product_form})

shop/templates/505.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
505 - Close this tab
{% endblock %}
{% block content %}
<br><br>
<h4 style="text-decoration: underline; text-align: center;">{% trans 'Please close this tab first then browser and re-scan QR Code' %} </h4>
<br>
<img src="{% static 'img/sorry.jpg' %}" height="300" width="380"/>
{% endblock %}

shop/templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Burgerize{% endblock %}</title>
    {% ifequal LANGUAGE_CODE 'ar' %}
    <link rel="stylesheet" href="{% static 'css/cairo.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endifequal %}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <!-- <link href="{% static "css/base.css" %}" rel="stylesheet"> -->
    <script src="{% static 'js/websocketbridge.js' %}" type="text/javascript"></script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script defer src="{% static "fontawesome/js/all.js" %}"></script>

</head>

<body style="background-color: white; #background-image: url({% static 'img/cover.jpg' %}); background-repeat: no-repeat; background-size: cover;">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <img src="{% static 'img/burgerize.jpg' %}" height="80" width="200"/>
        <nav class="my-2 my-md-0 mr-md-3">
           
        </nav> 
        {% if not request.user.is_superuser %}
        {% for language in languages %}
        {% if language.code != LANGUAGE_CODE %}
        <a class="btn btn-outline-warning" href="/{{ language.code }}/" 
        style="float: right; text-align: right; color: black; font-family: 'Cairo', sans-serif;">{{ language.name_local }}
         <i class="fas fa-globe" style="color: #eb842d;"></i></a> 
         {% endif %}
         {% endfor %}
         {% endif %}
    </div>
 
            <div class="container{% if request.user.is_superuser %}-fluid{% endif %}">
            {% if request.user.is_superuser %} 
            <div class="row">
            <div class="col col-lg-4">
            <a href="/takeout"><button class="btn btn-primary btn-bg btn-block" style="font-size: 25px;">Take Out</button> </a>
            </div>
            <div class="col col-lg-4">
            <a href="/orders/admin"><button class="btn btn-primary btn-bg btn-block" style="font-size: 25px;">Table Manager</button> </a>
            </div>
            <div class="col col-lg-4">
            <a href="/admin/shop/item"><button class="btn btn-primary btn-bg btn-block" style="font-size: 25px;">Item Inventory</button> </a>
            </div>
            </div>
            {% endif %}
            {% block content %}
            {% endblock %}
            </div>
</body>

</html>

shop/templates/list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="dropdown">
  <button class="btn dropdown-toggle" type="button" 
  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; background-color: #282322;">
    {% if not category %}
    {% trans 'All' %}
    {% else %}
    {{ category }}
    {% endif %}
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% if not category %}
    {% else %}
      <a class="dropdown-item" href="{% url "shop:item_list" %}">{% trans 'All' %}</a>
    {% endif %}
    {% for c in categories %}
    {% if c != category %}
      <a class ="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
    {% endif %}
    {% endfor %}
  </div>
  <a href="{% url 'cart:cart_detail' %}"><button class="btn" type="button" style="float: right; color: white; background-color: #eb842d;">
  {% trans 'Proceed' %} <i class="fas fa-angle-right"></i></button></a>
</div>



<br>

<div class="row" style="text-align: -webkit-center;">
{% for item in page_obj %}
  <div class="col-sm-6 col-md-6 col-lg-4" style="padding: 12px;">
    <div class="card" style="width: 20rem;">
      <img class="card-img-top" style="width: 19.9rem; height: 220px;" src="{% if item.image %}{{ item.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
      <div class="card-body">
        <h5 class="card-title">{{ item.name }}</h5>
        <h6><b>{{ item.price }} SDG </b></h6> <hr>
        <p class="card-text"><b>Ingredients:</b> {{ item.ingredients }}</p>
        <p>
          {% if item.name in cart_items %}

          <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
           <i class="fas fa-check-circle" style="color: green; font-size: 18px;"></i> <span class="selected">{% trans 'This item is selected' %}</span>
          {% else %}
          <form action="{% url "cart:cart_add" item.id %}" method="post">
            {{ cart_product_form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn" style="color: white; background-color: #eb842d;"><i class="fas fa-plus"></i> {% trans 'Add to order' %}</button>
          </form>
          {% endif %}
        </p>
      </div>
    </div>
  </div>
  <br>
{% endfor %}
</div>

<br><br>
  <div class="container">
  <div class="row justify-content-center">
  <nav aria-label="Page navigation example" style="justify-content: center;">
  {% if page_obj %}
  <ul class="pagination justify-content-end">
  {% if page_obj.has_previous %}
  <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" style="color: white; color: #eb842d;">{% trans 'Previous' %}</a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">{% trans 'Previous' %}</a>
    </li>
  {% endif %}
  {% for i in paginator.page_range %}
  {% if page_obj.number == i %}
    <li class="page-item active" style="z-index: 0; background-color: #eb842d; border-color: #eb842d;">
      <a class="page-link" href="#" style="color: white; background-color: #eb842d; border-color: #eb842d;">{{ i }} <span class="sr-only">(current)</span></a>
    </li>
  {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}" style="color: white; color: #eb842d;">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" style="color: white; color: #eb842d;">{% trans 'Next' %}</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">{% trans 'Next' %}</a>
    </li>
    {% endif %}
  </ul>
{% endif %}
</nav>
</div>
</div>
<br>
{% endblock %}

shop/templates/takeout.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}
Take-out
{% endblock %}
{% block content %}
<br><br>
<div class="dropdown">
  <button class="btn dropdown-toggle" type="button" 
  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; background-color: #282322;">
    {% if not category %}
    {% trans 'All' %}
    {% else %}
    {{ category }}
    {% endif %}
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% if not category %}
    {% else %}
      <a class="dropdown-item" href="{% url "shop:take_out" %}">{% trans 'All' %}</a>
    {% endif %}
    {% for c in categories %}
    {% if c != category %}
      <a class ="dropdown-item" href="{% url 'shop:take_out_by_category' c.slug %}">{{ c.name }}</a>
    {% endif %}
    {% endfor %}
  </div>
  <a href="{% url 'cart:cart_detail' %}"><button class="btn" type="button" style="float: right; color: white; background-color: #eb842d;">
  {% trans 'Proceed' %} <i class="fas fa-angle-right"></i></button></a>
</div>



<br>

<div class="row" style="text-align: -webkit-center;">
{% for item in items %}
  <div class="col-sm-6 col-md-6 col-lg-2" style="padding: 12px;">
    <div class="card" style="width: 17rem;">
      <img class="card-img-top" style="width: 16.9rem; height: 220px;" src="{% if item.image %}{{ item.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
      <div class="card-body">
        <h5 class="card-title">{{ item.name }}</h5>
        <h6><b>{{ item.price }} SDG </b></h6> <hr>
        <p>
          {% if item.name in cart_items %}

          <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
           <i class="fas fa-check-circle" style="color: green; font-size: 18px;"></i> <span class="selected">{% trans 'This item is selected' %}</span>
          <br><br><br><br>
          {% else %}
          <form action="{% url "cart:cart_add" item.id %}" method="post">
            {{ cart_product_form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn" style="color: white; background-color: #eb842d;"><i class="fas fa-plus"></i> {% trans 'Add to order' %}</button>
          </form>
          {% endif %}
        </p>
      </div>
    </div>
  </div>
  <br>
{% endfor %}
</div>

<br><br>
{% endblock %}