cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

handler500 = 'shop.views.handler500'

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webpush/', include('webpush.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'orders'

urlpatterns = [
    path('admin/', views.order_list, name='order_list'),
    path('create/', views.create_order, name='create_order'),
    path('process/<int:order_id>', views.process_order, name='process_order'),
    path('process/table/<int:table_number>', views.process_table, name='process_table'),
    path('takeout/process', views.create_order_admin, name='create_order_admin'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('<int:table_id>', views.item_list, name='item_list_by_table'),
    path('<slug:category_slug>/', views.item_list,
    name='item_list_by_category'),
    path('takeout', views.take_out, name='take_out'),
    path('takeout/<slug:category_slug>/', views.take_out, name='take_out_by_category'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

ITEM_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddItemForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=ITEM_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Item
from .cart import Cart
from .forms import CartAddItemForm

@require_POST
def cart_add(request, item_id):
    cart = Cart(request)
    item = get_object_or_404(Item, id=item_id)
    print(item.category)
    form = CartAddItemForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(item=item,
        quantity=cd['quantity'],
        update_quantity=cd['update'])
    print("success")
    return redirect(request.META['HTTP_REFERER'])

def cart_remove(request, item_id):
    cart = Cart(request)
    item = get_object_or_404(Item, id=item_id)
    cart.remove(item)
    return redirect('cart:cart_detail')



def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddItemForm(
                                initial={'quantity': item['quantity'],
                                'update': True})
    return render(request, 'detail.html', {'cart': cart})

cart/templates/detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
Your Order
{% endblock %}
{% block content %}
<h4 style="text-align: center; text-decoration: underline; font-family: 'Cairo', sans-serif;">{% trans 'Confirm Your Order' %}</h4><br>

<table class="table">
  <thead>
    <tr>
      <th scope="col">{% trans 'Item' %}</th>
      <th scope="col">{% trans 'Quantity' %}</th>
      <th scope="col">{% trans 'Price' %}</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart %}
    {% with product=item.item %}
    <tr>
      <td scope="row">{{ item.quantity }}x{{ product.name }}</td>
      <td>
                <form action="{% url "cart:cart_add" product.id %}" method="post">{{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <button class="btn" type="submit" style="color: white; background-color: #eb842d;">{% trans 'Update' %}</button>
                {% csrf_token %}
                </form>
        </td>
      <td>{{ item.total_price }}</td>
      <td><a href="{% url "cart:cart_remove" product.id %}" style="color: red;">X</a></td>
    </tr>
    {% endwith %}
  {% endfor %}
  <tr>
      <th scope="col">{% trans 'Total' %}</th>
      <th scope="col"></th>
      <th scope="col">{{ cart.get_total_price }} SDG</th>
      <th scope="col"></th>
    </tr>
    </tbody>
</table>
<br>
<a href="{% url "shop:item_list" %}" style="float:left;"><button type="button" class="btn" style="color: white; background-color: #282322;">{% trans 'Back to Menu' %} </button></a>
{% if cart|length > 0 %}
{% if request.user.is_superuser %}
<a href="{% url "orders:create_order_admin" %}" style="float:right;"><button type="button" class="btn" style="color: white; background-color: #eb842d;">{% trans 'Confirm' %}</button></a>
{% else %}
<a href="{% url "orders:create_order" %}" style="float:right;"><button type="button" class="btn" style="color: white; background-color: #eb842d;">{% trans 'Confirm' %}</button></a>
{% endif %}
{% endif %}
<br><br>
{% endblock %}